name = "seriousben"
license = ""
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.0.0"

[author]
    name = "Benjamin Boudreau"
    homepage = "https://seriousben.com"
