---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: seriousben/seriousben-com:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: blog
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
spec:
  rules:
  - host: seriousben.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 80
---
