---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: seriousben/seriousben-com:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: blog
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - seriousben.com
    secretName: seriousben-com-tls
  rules:
  - host: seriousben.com
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
---
