baseURL = "/"
theme = "cocoa-eh"
languageCode = "en-us"
title = "Benjamin Boudreau"
canonifyurls = true
author = "Benjamin Boudreau"
pluralizeListTitles = true
googleAnalytics = "UA-91134611-1"
disqusshortname = ""

[taxonomies]
category = "categories"

[permalinks]
blog = "/blog/:year/:month/:day/:slug"

[params]
align_left = false
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Benjamin Boudreau's blog"
copyright = "Copyright © 2017-2018 Benjamin Boudreau"
logoFile = ""
faviconFile = ""
highlightjs = true
progressively = true
share = true
latestpostcount = 5
usesmallsummarycard = true
posts_navigation = true
small_banner_logo = false

github = "seriousben"
linkedin = "boudreaubenjamin"
twitter = "@seriousben"
