---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: continuous-deployment
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingress"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "services", "pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: continuous-deployment
subjects:
- kind: User
  name: seriousben-com-deployer@projects-seriousben.iam.gserviceaccount.com 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io
---
