name: "Blogger"

on:
  schedule:
    # hourly 7to8 ET
    - cron: '15 10-23 * * *'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  blog:
    name: "Blog"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: "1.26"

    - if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: |
        go install "github.com/seriousben/positronic-blogger/cmd/positronic-sync@v1.1.2"

        $(go env GOPATH)/bin/positronic-sync
      env:
        POSITRONIC_GITHUB_REPO: seriousben/seriousben.com
        # Using specific repo scoped token to trigger other actions.
        POSITRONIC_GITHUB_TOKEN: ${{ secrets.POSITRONIC_GITHUB_TOKEN }}
        POSITRONIC_NEWSBLUR_USERNAME: ${{ secrets.POSITRONIC_NEWSBLUR_USERNAME }}
        POSITRONIC_NEWSBLUR_PASSWORD: ${{ secrets.POSITRONIC_NEWSBLUR_PASSWORD }}
        POSITRONIC_NEWSBLUR_CONTENT_PATH: content/links
        POSITRONIC_NEWSBLUR_CHECKPOINT_PATH: content/links/checkpoint
        # POSITRONIC_SKIP_MERGE: true